package model

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ManifestFile is the per-project state file written at the project root.
const ManifestFile = ".kmp-scaffold.json"

// ManifestSchema is bumped whenever the manifest layout changes incompatibly.
//
// Schema 1 was Kotlin Multiplatform shaped: the layout ids, library packs and
// shared utilities were fields of the manifest itself. Schema 2 splits that
// into the part every template has (the project's identity and its features)
// and a template-defined `vars` blob, so a project generated from any template
// can be described by the same file.
const ManifestSchema = 2

// Project is the set of answers the tool asks for whatever template is in use.
type Project struct {
	Name          string `json:"name"`
	Package       string `json:"package,omitempty"`
	ApplicationID string `json:"applicationId,omitempty"`

	// Dir is where the project is being written. It is a property of this run,
	// not of the project, so it is never persisted.
	Dir string `json:"-"`
}

// PackagePath returns the package as a directory path: io/kontour/tunesic.
func (p Project) PackagePath() string { return strings.ReplaceAll(p.Package, ".", "/") }

// Namespace is the lowercased, alphanumeric form of the name, used for things
// like buildSrc convention plugin ids.
func (p Project) Namespace() string { return LowerAlnum(p.Name) }

// TypePrefix is the PascalCase form of the name, used to name generated types.
func (p Project) TypePrefix() string { return Pascal(p.Name) }

// Kebab is the kebab-case form of the name, used for default directories.
func (p Project) Kebab() string { return Kebab(p.Name) }

// TemplateRef records which template generated a project, and where that
// template came from, so `add` can load the same one again.
type TemplateRef struct {
	ID     string `json:"id"`
	Source string `json:"source,omitempty"` // "builtin", a path, or a remote ref
	// Revision pins a remote template to the commit the project was generated
	// from, so adding to a project years later does not silently use a
	// different version of the template.
	Revision string `json:"revision,omitempty"`
	Version  string `json:"version,omitempty"`
}

// Manifest is what gets written into the generated project.
type Manifest struct {
	Schema       int             `json:"schema"`
	GeneratorVer string          `json:"generatorVersion"`
	Template     TemplateRef     `json:"template"`
	Project      Project         `json:"project"`
	Vars         json.RawMessage `json:"vars,omitempty"`
	Features     []Feature       `json:"features,omitempty"`

	// Migrated records that this manifest was read from an older schema. It is
	// not persisted; it exists so a command can report the upgrade the first
	// time it writes the file back.
	Migrated bool `json:"-"`
}

// Feature records something a template's recipe added to the project. Name and
// Recipe are universal - together they are what stops the same thing being
// added twice - and Vars is whatever the template needs to remember about it.
type Feature struct {
	Name string `json:"name"`
	// Recipe is which of the template's recipes created this. It is absent in
	// manifests written before templates had more than one, where it means
	// "whatever recipe is asking".
	Recipe string          `json:"recipe,omitempty"`
	Vars   json.RawMessage `json:"vars,omitempty"`
}

// NewManifest builds a manifest for a freshly generated project.
func NewManifest(version string, ref TemplateRef, project Project, vars any, features []Feature) (Manifest, error) {
	m := Manifest{
		Schema:       ManifestSchema,
		GeneratorVer: version,
		Template:     ref,
		Project:      project,
		Features:     features,
	}
	if err := m.SetVars(vars); err != nil {
		return Manifest{}, err
	}
	return m, nil
}

// SetVars stores the template's own state.
func (m *Manifest) SetVars(vars any) error {
	if vars == nil {
		m.Vars = nil
		return nil
	}
	data, err := json.Marshal(vars)
	if err != nil {
		return fmt.Errorf("encoding the template's project settings: %w", err)
	}
	m.Vars = data
	return nil
}

// DecodeVars reads the template's own state into dst. Unknown fields are an
// error: a manifest field the template no longer understands means the project
// was generated by a different version of it, and guessing is worse than
// saying so.
func (m Manifest) DecodeVars(dst any) error {
	if len(m.Vars) == 0 {
		return nil
	}
	if err := json.Unmarshal(m.Vars, dst); err != nil {
		return fmt.Errorf("reading the template settings from %s: %w", ManifestFile, err)
	}
	return nil
}

// DecodeVars reads a feature's template-defined state into dst.
func (f Feature) DecodeVars(dst any) error {
	if len(f.Vars) == 0 {
		return nil
	}
	if err := json.Unmarshal(f.Vars, dst); err != nil {
		return fmt.Errorf("reading the settings for feature %q: %w", f.Name, err)
	}
	return nil
}

// NewFeature builds a feature record with its template-defined state encoded.
func NewFeature(recipe, name string, vars any) (Feature, error) {
	f := Feature{Name: name, Recipe: recipe}
	if vars == nil {
		return f, nil
	}
	data, err := json.Marshal(vars)
	if err != nil {
		return Feature{}, fmt.Errorf("encoding the settings for feature %q: %w", name, err)
	}
	f.Vars = data
	return f, nil
}

// FindFeature returns the recorded feature with the given name, whichever
// recipe created it.
func (m Manifest) FindFeature(name string) *Feature {
	for i := range m.Features {
		if m.Features[i].Name == name {
			return &m.Features[i]
		}
	}
	return nil
}

// FindFeatureOf returns the record a given recipe made under a name.
//
// Two recipes may each have an "auth"; the pair is what has to be unique. A
// record with no recipe matches any of them, because that is what a manifest
// written before a template had more than one recipe means.
func (m Manifest) FindFeatureOf(recipe, name string) *Feature {
	for i := range m.Features {
		f := &m.Features[i]
		if f.Name == name && (f.Recipe == "" || f.Recipe == recipe) {
			return f
		}
	}
	return nil
}

// PutFeature adds a feature record, replacing any earlier one the same recipe
// made under the same name.
func (m *Manifest) PutFeature(f Feature) {
	for i := range m.Features {
		if existing := &m.Features[i]; existing.Name == f.Name &&
			(existing.Recipe == "" || existing.Recipe == f.Recipe) {
			m.Features[i] = f
			return
		}
	}
	m.Features = append(m.Features, f)
}

// LoadManifest reads .kmp-scaffold.json from dir, walking up to the filesystem
// root so that `add` works from any subdirectory of a project.
//
// Older schemas are migrated in memory. Nothing is written back here: a command
// that only reads the project must not leave behind a file an older
// kmp-scaffold cannot open.
func LoadManifest(dir string) (*Manifest, string, error) {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return nil, "", err
	}
	for {
		candidate := filepath.Join(abs, ManifestFile)
		if data, err := os.ReadFile(candidate); err == nil {
			m, err := ParseManifest(data)
			if err != nil {
				return nil, "", fmt.Errorf("%s: %w", candidate, err)
			}
			return m, abs, nil
		}
		parent := filepath.Dir(abs)
		if parent == abs {
			return nil, "", fmt.Errorf("no %s found in %s or any parent directory - "+
				"run this from inside a project created by kmp-scaffold", ManifestFile, dir)
		}
		abs = parent
	}
}

// ParseManifest decodes a manifest, migrating older schemas.
func ParseManifest(data []byte) (*Manifest, error) {
	var probe struct {
		Schema int `json:"schema"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return nil, fmt.Errorf("parsing: %w", err)
	}
	if probe.Schema > ManifestSchema {
		return nil, fmt.Errorf(
			"written by a newer kmp-scaffold (schema %d, this build understands %d)",
			probe.Schema, ManifestSchema)
	}
	if probe.Schema < ManifestSchema {
		return migrateManifest(data, probe.Schema)
	}

	var m Manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parsing: %w", err)
	}
	return &m, nil
}

// Save writes the manifest to the given project root.
func (m Manifest) Save(root string) error {
	m.Schema = ManifestSchema
	data, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return os.WriteFile(filepath.Join(root, ManifestFile), data, 0o644)
}

// ---------------------------------------------------------------------------
// Migration
// ---------------------------------------------------------------------------

// schema1 is the shape of the manifest before templates existed. It is frozen:
// projects generated by earlier versions of the tool still have this on disk,
// and this struct is the only thing that can read them.
type schema1 struct {
	GeneratorVer  string `json:"generatorVersion"`
	Name          string `json:"name"`
	Package       string `json:"package"`
	ApplicationID string `json:"applicationId"`
	Android       bool   `json:"android"`
	IOS           bool   `json:"ios"`
	AndroidLayout string `json:"androidLayout"`
	IOSLayout     string `json:"iosLayout"`

	SharedUtils   []string `json:"sharedUtils"`
	AndroidExtras []string `json:"androidExtras"`
	Packs         []string `json:"packs"`
	RootTabs      []string `json:"rootTabs"`

	Features []struct {
		Name         string `json:"name"`
		Android      bool   `json:"android"`
		Shared       bool   `json:"shared"`
		IOS          bool   `json:"ios,omitempty"`
		Presentation string `json:"presentation"`
		RootTab      bool   `json:"rootTab"`
	} `json:"features"`
}

// BuiltinKMPTemplate is the id of the template every schema-1 project was
// generated from - there was only one.
const BuiltinKMPTemplate = "kmp-mobile"

func migrateManifest(data []byte, schema int) (*Manifest, error) {
	var old schema1
	if err := json.Unmarshal(data, &old); err != nil {
		return nil, fmt.Errorf("parsing a schema-%d manifest: %w", schema, err)
	}

	// Everything that used to be a manifest field becomes the KMP template's
	// vars, under the same JSON names, so the projection is lossless and the
	// template reads it with no special cases.
	vars := map[string]any{
		"android":       old.Android,
		"ios":           old.IOS,
		"androidLayout": old.AndroidLayout,
		"iosLayout":     old.IOSLayout,
		"sharedUtils":   nonNil(old.SharedUtils),
		"androidExtras": nonNil(old.AndroidExtras),
		"packs":         nonNil(old.Packs),
		"rootTabs":      nonNil(old.RootTabs),
	}

	m := Manifest{
		Schema:       ManifestSchema,
		GeneratorVer: old.GeneratorVer,
		Template:     TemplateRef{ID: BuiltinKMPTemplate, Source: "builtin"},
		Project: Project{
			Name:          old.Name,
			Package:       old.Package,
			ApplicationID: old.ApplicationID,
		},
		Migrated: true,
	}
	if err := m.SetVars(vars); err != nil {
		return nil, err
	}

	for _, f := range old.Features {
		rec, err := NewFeature("feature", f.Name, map[string]any{
			"android":      f.Android,
			"shared":       f.Shared,
			"ios":          f.IOS,
			"presentation": f.Presentation,
			"rootTab":      f.RootTab,
		})
		if err != nil {
			return nil, err
		}
		m.Features = append(m.Features, rec)
	}
	return &m, nil
}

// nonNil keeps an absent list distinguishable from an empty one in the encoded
// vars: a schema-1 manifest with no packs meant "none", not "unset".
func nonNil(v []string) []string {
	if v == nil {
		return []string{}
	}
	return v
}
