package cli

import (
	"bufio"
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/aaroncutress/kmp-scaffold/internal/catalog"
	"github.com/aaroncutress/kmp-scaffold/internal/kmp"
	"github.com/aaroncutress/kmp-scaffold/internal/model"
	"github.com/aaroncutress/kmp-scaffold/internal/resolve"
)

var tomlVersionLine = regexp.MustCompile(`^([A-Za-z0-9_.\-]+)\s*=\s*"([^"]*)"`)

func runVersions(ctx context.Context, args []string) error {
	fs := flag.NewFlagSet("versions", flag.ContinueOnError)
	fs.Usage = func() {
		fmt.Fprint(os.Stderr, `Usage: kmp-scaffold versions [flags]

Compares the versions in this project's gradle/libs.versions.toml against the
newest releases, and reports what has moved on. Nothing is modified.

Run outside a project to see what a fresh project would use instead.

Flags:
`)
		fs.PrintDefaults()
	}

	var (
		dir     = fs.String("dir", ".", "Project directory")
		channel = fs.String("channel", "", "Version channel: stable, preview or bleeding")
		all     = fs.Bool("all", false, "Show every version key, not just the outdated ones")
	)
	if err := fs.Parse(args); err != nil {
		return ErrUsage
	}

	manifest, root, err := model.LoadManifest(*dir)
	if err != nil {
		// Outside a project: still useful as "what would I get today?".
		spec := defaultSpec(*channel)
		fmt.Println(sMuted.Render("Not inside a kmp-scaffold project - showing what a new project would use.\n"))
		result := resolve.Run(ctx, kmp.RequestFor(spec))
		printVersionTable(result)
		printResolveNotes(result)
		return nil
	}

	if id := manifest.Template.ID; id != "" && id != kmp.ID {
		return fmt.Errorf(
			"`versions` reads a %s project's version catalog; this one was generated by the %q template",
			kmp.ID, id)
	}
	spec, _, err := kmp.SpecFrom(manifest)
	if err != nil {
		return err
	}
	if *channel != "" {
		spec.Channel = *channel
	} else {
		spec.Channel = "preview"
	}

	current, err := readCatalogVersions(filepath.Join(root, "gradle/libs.versions.toml"))
	if err != nil {
		return err
	}

	fmt.Println(sBold.Render("Checking " + manifest.Project.Name + " against the latest releases..."))
	latest := resolve.Run(ctx, kmp.RequestFor(spec))

	type row struct{ key, have, want string }
	var outdated, same []row

	for _, def := range catalog.VersionKeys() {
		have, ok := current[def.Key]
		if !ok {
			continue
		}
		want := latest.V(def.Key)
		if want == "" {
			continue
		}
		// SDK levels and app versions are project settings, not dependencies.
		switch def.Key {
		case catalog.KeyMinSDK, catalog.KeyVersionCode, catalog.KeyVersionName:
			continue
		}
		if have == want {
			same = append(same, row{def.Key, have, want})
			continue
		}
		if resolve.ParseVersion(want).Less(resolve.ParseVersion(have)) {
			// The project is ahead of what this channel offers - not outdated.
			same = append(same, row{def.Key, have, want})
			continue
		}
		outdated = append(outdated, row{def.Key, have, want})
	}

	fmt.Println()
	if len(outdated) == 0 {
		fmt.Println(sOK.Render("✔ Everything is on the newest " + spec.Channel + " release."))
	} else {
		width := 0
		for _, r := range outdated {
			if len(r.key) > width {
				width = len(r.key)
			}
		}
		for _, r := range outdated {
			fmt.Printf("  %-*s  %s  %s  %s\n", width, r.key,
				sMuted.Render(r.have), sMuted.Render("→"), sAccent.Render(r.want))
		}
		fmt.Println()
		fmt.Println(sMuted.Render(fmt.Sprintf(
			"%d of %d entries have newer releases. Edit gradle/libs.versions.toml to take them.",
			len(outdated), len(outdated)+len(same))))
	}

	if *all && len(same) > 0 {
		fmt.Println()
		fmt.Println(sBold.Render("Up to date"))
		for _, r := range same {
			fmt.Printf("  %s  %s\n", r.key, sMuted.Render(r.have))
		}
	}

	printResolveNotes(latest)
	return nil
}

// readCatalogVersions parses the [versions] block of a version catalog.
func readCatalogVersions(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("reading the version catalog: %w", err)
	}
	defer f.Close()

	versions := map[string]string{}
	inVersions := false
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "[") {
			inVersions = line == "[versions]"
			continue
		}
		if !inVersions || line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if m := tomlVersionLine.FindStringSubmatch(line); m != nil {
			versions[m[1]] = m[2]
		}
	}
	return versions, scanner.Err()
}
