// Package kmp is the Kotlin Multiplatform template: the Compose Android app,
// the SwiftUI iOS app and the shared KMP module this tool started life
// generating.
//
// It is a thin adapter. The generation itself still lives in
// internal/generator, the libraries in internal/catalog and the answers in
// model.Spec; this package is what presents all of that to the rest of the tool
// as one scaffold.Template.
package kmp

import (
	"fmt"

	"github.com/aaroncutress/kmp-scaffold/internal/model"
	"github.com/aaroncutress/kmp-scaffold/internal/scaffold"
)

// ID is this template's name on the command line.
const ID = model.BuiltinKMPTemplate

// Vars is what this template records in a generated project's manifest: the
// structural answers a later `add` has to know in order to match how the
// project was built.
//
// The JSON names match the fields the schema-1 manifest had, so a project
// generated before templates existed migrates into exactly this shape.
type Vars struct {
	Android       bool     `json:"android"`
	IOS           bool     `json:"ios"`
	AndroidLayout string   `json:"androidLayout"`
	IOSLayout     string   `json:"iosLayout"`
	SharedUtils   []string `json:"sharedUtils"`
	AndroidExtras []string `json:"androidExtras"`
	Packs         []string `json:"packs"`
	RootTabs      []string `json:"rootTabs"`
}

// FeatureVars is what this template records about each feature it added.
type FeatureVars struct {
	Android      bool   `json:"android"`
	Shared       bool   `json:"shared"`
	IOS          bool   `json:"ios,omitempty"`
	Presentation string `json:"presentation"`
	RootTab      bool   `json:"rootTab"`
}

// VarsOf projects a spec into the form a generated project remembers.
func VarsOf(spec model.Spec) Vars {
	return Vars{
		Android:       spec.Android,
		IOS:           spec.IOS,
		AndroidLayout: spec.AndroidLayout,
		IOSLayout:     spec.IOSLayout,
		SharedUtils:   spec.SharedUtils,
		AndroidExtras: spec.AndroidExtras,
		Packs:         spec.Packs,
		RootTabs:      spec.RootTabs,
	}
}

// SpecFrom rebuilds enough of a Spec from a project manifest for the templates
// to generate against, so an added feature matches how the project was made.
//
// The manifest is decoded into a typed struct rather than read field by field
// out of a map, because a missing "rootTab" silently becoming false would mean
// a re-added tab quietly stops joining the navigation shell.
func SpecFrom(m *model.Manifest) (model.Spec, Vars, error) {
	if m.Template.ID != "" && m.Template.ID != ID {
		return model.Spec{}, Vars{}, fmt.Errorf(
			"this project was generated by the %q template, not %q", m.Template.ID, ID)
	}

	var vars Vars
	if err := m.DecodeVars(&vars); err != nil {
		return model.Spec{}, Vars{}, err
	}

	spec := model.Spec{
		Name:          m.Project.Name,
		Package:       m.Project.Package,
		ApplicationID: m.Project.ApplicationID,
		Android:       vars.Android,
		IOS:           vars.IOS,
		AndroidLayout: vars.AndroidLayout,
		IOSLayout:     vars.IOSLayout,
		SharedUtils:   vars.SharedUtils,
		AndroidExtras: vars.AndroidExtras,
		Packs:         append([]string(nil), vars.Packs...),
		RootTabs:      vars.RootTabs,
		JVMTarget:     "11",
	}
	return spec, vars, nil
}

// FeatureVarsOf reads what this template recorded about a feature.
func FeatureVarsOf(f model.Feature) (FeatureVars, error) {
	var v FeatureVars
	err := f.DecodeVars(&v)
	return v, err
}

// Spec is this template's typed view of an answer bag.
//
// The universal answers live on the bag, so they are copied across on every
// read: the wizard writes a project name into Answers.Project, and the spec has
// to see it.
func Spec(a *scaffold.Answers) *model.Spec {
	spec, ok := a.State().(*model.Spec)
	if !ok {
		spec = &model.Spec{}
		*spec = model.Defaults()
		a.SetState(spec)
	}
	spec.Name = a.Project.Name
	spec.Dir = a.Project.Dir
	spec.Package = a.Project.Package
	spec.ApplicationID = a.Project.ApplicationID
	return spec
}
